---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mirror
  namespace: common
spec:
  encryptedData:
    values.yaml: AgAi6EzI8QteZ2gUEn3BFbvqJoEuo99rInWmcaCEmXqoiD2Yhy7/3I35x0MPUx5rpO9+nAynrd8tPIg6MwvSWhu04pD8kAKlIRfKsEeB4t22fy8/hjDjaOxu+cuXO6pVjeTjdY+GFkBFxOVCnV0L4o/l/C45t12Z7iL7LDZkUcm7tS8IYsLR+DUGGk4pZ3qqndjHQit8uP1/WFjhbYeeFnufbiDi6eAcZv9DVHbagQX/188/oyjwwJ1YMRVru1Zy39Und2kmUAshg8fy/BBGg79OsZ9oDg2OVyeCUSRwQECAomiFZPdAhz2sodwEf/RiskT3nu+W9+3x3+aqIB55tpTd5wVibGN8aqsk9D7OjWriSmsbHuLANd+UYdHvrjAYPuN0LFpggPGcB+csO0Cx1+PtETRRNvsPR/QrBMIjh49GbZDCfYGee5L+YMu+IHBsR+oCAtLe4xVIOkYALA9Bg+4vV/M1n+k65CDm5NHmCBvivAHnxEeP6awaqHtfUbHF+IKcv1AUUTqZFsBCQci+FPNDLweOYjdp1XK+nR7+OjLNF4EZTpqwsZ0JsqQn6IpEBFaqkPKm1J0cZfxgl4R8KBpc5gJqDDcAVp3W4Wj0a/GnUc5Cx4gYQboP2aQDPiDe1poA9g0aS2rZGLhmWQT7/bHV2jGIM/fVC7cqknUliXcCmwNuYYPcw3Mnk6nhr3ljcTHOkmpNd270X9ESJ76RwMuvWoObz1KWH1YnNeAM+vGdbAKugxDe4KaqOr10dB8nNXBIw+gskptNbDC98rlG3anr4/w3Pfoad5Qx6atzNEIVG8AqNUZzd+8P23lFGo6Twa33xiY5F6lN7JLAYZAO++kALrtPNj2iBOfUAkKTEdHh0Q==
  template:
    metadata:
      creationTimestamp: null
      name: mirror
      namespace: common
    type: Opaque
