---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mirror
  namespace: common
spec:
  encryptedData:
    values.yaml: AgBe1q/2uID3uzw+d4CJ6QEPTW+cdkeHZmt5ZopLQTz9Yu1YQCT4LDevRfOrJRJrTeiIXuV1K7vJn18edchOfh7cHFvGLxZhqVkwCwYpL7j55nwbCPiKibJoHnGnAADKQRSV/l3niWYbVmtXnwD5LcMiFZy+UvpJQNDr9lyLR/McfycFhzKUkPAGd8G8HuBrpS5rcIByjWJXHU/UarXfGYIvXalZjQkg80LTuo/9rWoNorBpVQc3ISGn7ohrXGdxAp2zIhdG54wm5dUwNiXisD5fhri4jaQzcc5kBE8NiSEiFwL/dIPL4mu4kjYidUeSlJ5vwIYteyNR4lNEDKV4XEYw40W9S1nGhhiXoe1OyUIh/V87PIhaLsDH8eiHNU6R+Ff5z6CdBl160vLPEExhIESjSe+fqiGiuMp/AD+ErTxXJWAcwwwqq1Q/arZ/YIkJywOSmOqSmK4lzXVVFpnOygxOTaAWdvtg5qrfce883NHrLk8OE5fnK6uAv31KrWwgWpcjmGvXCc+VaoGojiNw12MnLyIKRAJPhlUD/0HBZQuAqOvqLgj+l+Zzqg237vrjW/o0+wgDp9E34heDOfizTIR7yskG5YZiKEm7hA+dtQE7X7ZGkOsPezKyzEzlbSVm+mNe7LXpUWnkynt898rYQ8BDQrUmT15h3OxabUFWGZ7ozckcwzt2B72zZO0l/ZWyer+mdIp9rtF0PlpzdYLlYRZ/M6pyngo9YeVjXoIRDSCR47S8ppWpXyZKaMxQrr1QskqGAlVwZcHFoI4GD4YStKZD692XuJuUDLTfLZbU9SUpKa3u8xd4Ttjt8a1x6dStDo/z0oa6nYNtjcx19V9O+cmHWQxX1+HgF4x+2rzj9pFc0A==
  template:
    metadata:
      creationTimestamp: null
      name: mirror
      namespace: common
    type: Opaque
