---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgBUlubIpWcsYLr3oMJf8Izp7sL5Pm4JkY3J+uraB+rb3WhJkJqacUCPb55gRk21elwnB5lniLFSEOsUrkRdEcBwgeZEvvoABrELC0gAoqn8XdP3VkOP8R3S3a0IIDTKbYY/osUShpHQt75kblnu2To5jF8id2hYn1HP92H1pmvjfwG40uzR0lE/xqb01FvH3lTV/TvTtVuT7jXa2y2I7Q6QAkxMtBlP4ZWX6VpXl2ZFYiusfxvHKlEDyWQq2OXWiknGoIh81tS3RQL55zaeZoT5g+ZnMBxvLCXuDlkMmHN6qpmUSuJkSXYBJadGQ0Svdz8oFh6A71lA1qU/7rs2iN7OsZy0nlE0ajDigHSC0jiho+1YIJ8zXxFHc8lDyzlBxeCBxDrr5MGj0sVlGYF4FmqmEDkAnZgh08pdaaZ0YmgTQ/pi4fTu7w7C+k6jgxLheMSKCT1DM2/xvsWdrlgI6p9XWgnuU5044WPE2FoSsF/pJDpmj5Bm8D1mYAXR6piRKKNUVTBIckpTXZn1q6Zf4Dmp8i5G07wi93DGwiilJPSSGUVp0NQ7n4YmZT5lhRZXqHQ3tttVIg4mk6vKApKD76unz6PfPP9o2gGk6Rl3xmbpF8+1fOZLr/a9+IFEkfZEn3YbmGOiJwTCX78Z0X9puvqbqjG59pss+dnGsDTfxbx7F2ykqHUasqcN6BhqCX+O7KCb/rJX4VUeQjFeW2zSv1FTor4rUVO5YEYUKF5seBgrCqpIyU5vJQ==
    token: AgCPdtMtkFBzrenYu8AkwMKiELejYJ8geVQmvQ8DUKzrlnLubgWw+SLNkH0Ck6AKZfb4b4CrXwanmbv+QJFI+6Mol38MqJlvyvYhpx0huYeSfyR2JqtWRurXkkB4DfElu+1jCpFynIJP+FyKuCcOXgI/duncGkusQzTb8/lj2Baagk1z5z0NUhTZbuzKjy4t0fk53N1pCS7+1RsXIOG2HMNm4Pfg7F+FBF90I1xTasHF/Zpy5yHJgFDq0xyAVl9SOBGSy0kVTHv4+O9/l+V6cinAc2ieoMe2kY/Ah7RGl7gwf5ilZ8QwK7jXt4mDAK0DZJ3/bAHvvp47stO1ou0hyHHzTZDk3tPAESvjaXpVcAxWLLvSDeMVcvEpYCLfuoSQC+3d+Vxlef3UtPigL/ey1ZK0HYjYFTL3siEVUJAHBaauu27RqN173kEpSIcDUt6Zz7W1pa/FftE+nP7S4q4OYLFZCLxc4CfHb/jt0SVOghMQ0n+52gafB8Zz4oSzhJ6mpUkR6nb9ug16vGa3nI2UpGzy0ptP08c+l8bfxTMceCg3gP77qfMSNFVJzBTJ2hzXWoQ9JR25LDqhyvMiP8/dCrvD/zaUsnuVvmsIxcJH1JFi7GxIAnPcmQ6cYnzhNQ4tyY9sh6YAZMWUFoeKkFS4LPnAiWPNAEaWyoaEIsFhvn3BBanqYZFRxLi7IIiaTemPEttH7h1r8lG83NXO8NSinoTvSk8WIYypGYM3yZWpelLhMtygK6Lfj4i+RmdPLV5oLsnrzuVGX4xWugs=
  template:
    metadata:
      name: slack
      namespace: flux-system
    type: Opaque
