# SPDX-License-Identifier: Apache-2.0

chart-repos:
  - bitnami=oci://registry-1.docker.io/bitnamicharts
  - loki=https://grafana.github.io/helm-charts
  - prometheus=https://prometheus-community.github.io/helm-charts
  - traefik=https://helm.traefik.io/traefik
check-version-increment: false
validate-maintainers: false
