# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: "gradle"
    schedule:
      interval: "weekly"

  - directory: "/charts"
    open-pull-requests-limit: 10
    package-ecosystem: "helm"
    schedule:
      interval: "weekly"

  - directory: "/rest"
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/rest/monitoring"
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/rest/check-state-proof"
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/rosetta"
    open-pull-requests-limit: 10
    package-ecosystem: "gomod"
    schedule:
      interval: "weekly"

  - directory: "/tools/traffic-replay/log-downloader"
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/tools/mirror-report"
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
