# SPDX-License-Identifier: Apache-2.0

importer:
  config:
    hiero:
      mirror:
        importer:
          block:
            nodes:
              - endpoints:
                  - apis: [STATUS]
                    host: "block-node-1.${SOLO_NAMESPACE}.svc.cluster.local"
                    port: 40982
                  - apis: [SUBSCRIBE_STREAM]
                    host: "block-node-1.${SOLO_NAMESPACE}.svc.cluster.local"
                    port: 40980
  env:
    SPRING_PROFILES_ACTIVE: "blocknode"
