# SPDX-License-Identifier: Apache-2.0

codecov:
  notify:
    after_n_builds: 7 # We upload multiple separate reports, one for each GitHub action
comment:
  after_n_builds: 7
coverage:
  status:
    project:
      default:
        threshold: 1.0
ignore:
  - "hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/**/*"
