apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgCDNewkYJ5hXsrvNwevTR4fSHku7THI2YAeeF5s/HRMlGibezJU9cMsWWtAA3Vs5jn2M/P9UFgjav71h+Y5YvWsCoFMCdWIexIJ8IMf+QKohdXGNSilv6kf/CgBgFwVBl1Jf6/6bRygRlL40OWmHC1scGHk3UKENa5BG8OQnYg/+zMNuS0C3/xfiPTOS+c3ifvugUR+xCh6ABkrGEEQomAecR6GObkQpiwUcYtKq4Hg/5Eys+wyQXOMIq+rAU2vGDfGHqY77Ph6fxX+2AmEfoCIwBwpUQAar0URThWUT54VXlKROFsnLfSJMUNAnofYTqUcwks3nzo/w95uovJ6BQewIr4mcRaYXHMUuEMacr4N2Z4Eyz8mnT58mMpORPeHYHlfTkPyD5P9t+jhYDlJrRYS/sDTeYSLcTw2TJV8a9wiyeFaMEUQiLFNyHfkXNF2fRgAN1wZvGKnLC0/TbkwaRO3dS2L1Bs1M4K6D8MwYLdeeBhMRRebPsWXfw3xWAWrdrWkbNaxvCEGIFVR0sZyf6FGbhUdPtWJYXXgYNG17b+3bKl3HjR6FzEhzff9EoXGYbSzsfp5XG/yUeWiZFKnClK/JvT/EEmBs/7NRNnlkqztlO6QTzDijqTPtOVg3dmEM3VsVJOsAiE30DRSi6+/Ig5wc2fNmyF2RZgad4BCJgbDgDVmyLCkEiT0jcaxT3tNCtg/EwKOb1mqIKI4+zUlA9jXpoUmfFv2mryJlTqm7eE/oM/D3bNxuK/FikBvJ3pK8L6vj9GLMrOlFBmdYfnfut8F/XuAEbaBgyPv93A73d8MWNSK49ZpTi5+NRKV+1DrxPurI9XTud35axf3+1+BptMvs6qpiQ==
    username: AgAHVjkbIQWf+GkQUI5D5Tt1pK/W/YemNNxVi4DMotGdzv2TJkx98CA6W70+98qEye2i5Bi2vghs2foRpwWUYipv2+bxOt55bqcnV12OI0wb+etcziOUkygz3ppMpQ7Qc4LPdTni2dM8S95QfxHNW7qUUfJvUKOQTxiYWKgXLVXB1jK5ZOIyEWOMYEHCc6irLy1iEsNTnaV8NsRv2gWqK6vMQH/p32fln5ET0hmUIsI/D+k8elFYFd4Q15XZ3s+mEUn8IOzFRyGtdwNqYTyBxz8c6qT1+NaBvNpGH898oCsxKwQvuf0FddH1SWwd+yS1WZpuU5XWDFjz0ooU3SCxCi9/hifJ2qCDQ66PFrUx15M8kG9PuaiothnMIPW3Gb9gzJeZ9Je8/fmJsgGxUYiVHunb14R7ZVff6ORSkdogmGSHEIjE4/B0iA8k1TsAbOcJTITZV1r88hT1a/SefPhpJ1dNKkCYd0M29/C2bW32v9XzWQ9BVCKDNs7SVkYfvhXD7ugZrFuvHQA8RzbuGy8Ovb7Sp0z3oOsa4uFMTb2mQnAcKl6wf9htQbpYILJTQRNdgUjWZxc5FxdnC3wNCsqp03Wp3dqptSM1+Mc0wfnc0vaHTML/K7ewNOTujPzXL4B5kXs849GNnEPU7GxhT3VokAzRwvYidAGuANJwCLUkkAFKz+tFJs2fE07JrEQw1Qh4l4d1jaYvthw=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-cloud
      namespace: common
    type: Opaque
