# SPDX-License-Identifier: Apache-2.0

properties:
  grpc.service.type:
    default: ClusterIP
    type: string
  importer.config.hiero.mirror.importer.downloader.accessKey:
    default: ""
    type: string
  importer.config.hiero.mirror.importer.downloader.cloudProvider:
    type: string
    default: S3
  importer.config.hiero.mirror.importer.downloader.secretKey:
    default: ""
    type: string
  importer.config.hiero.mirror.importer.network:
    default: "DEMO"
    type: string
  rest.service.type:
    default: ClusterIP
    type: string
