# SPDX-License-Identifier: Apache-2.0

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{ include "hedera-mirror-rosetta.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-rosetta.serviceAccountName" . }}
  namespace: {{ include "hedera-mirror-rosetta.namespace" . }}
{{- end -}}
