# SPDX-License-Identifier: Apache-2.0

{{ if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{ include "hedera-mirror-graphql.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-graphql.serviceAccountName" . }}
  namespace: {{ include "hedera-mirror-graphql.namespace" . }}
{{- end -}}
