{
 "title": "AlertManager",
 "tags": [
  "alertmanager",
  "alerts",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(ALERTS, cluster)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(ALERTS{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(alertmanager_build_info)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(ALERTS{cluster=~\"$cluster\",namespace=~\"$namespace\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Name",
   "type": "piechart",
   "description": "The percent of alerts firing by name",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{cluster=~\"$cluster\",namespace=~\"$namespace\",alertname!=\"Watchdog\",container=~\"$container\"}) by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Severity",
   "type": "piechart",
   "description": "The percent of alerts by severity",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{cluster=~\"$cluster\",namespace=~\"$namespace\",alertname!=\"Watchdog\",container=~\"$container\"}) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "State",
   "type": "piechart",
   "description": "The percent of alerts by state",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{cluster=~\"$cluster\",namespace=~\"$namespace\",alertname!=\"Watchdog\",container=~\"$container\"}) by (alertstate)",
     "legendFormat": "{{alertstate}}"
    }
   ]
  },
  {
   "title": "AlertManager Instances",
   "type": "stat",
   "description": "The number of AlertManager pods",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(alertmanager_build_info{cluster=~\"$cluster\",namespace=~\"$namespace\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",cluster=~\"$cluster\",namespace=~\"$namespace\",instance=~\"$instance\",alertname!=\"Watchdog\",container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Suppressed Alerts",
   "type": "stat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(alertmanager_alerts{state=\"suppressed\",cluster=~\"$cluster\",namespace=~\"$namespace\",instance=~\"$instance\",container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Silenced Alerts",
   "type": "stat",
   "description": "Current number of silenced alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(alertmanager_silences{state=\"active\",cluster=~\"$cluster\",namespace=~\"$namespace\",instance=~\"$instance\",container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "description": "Alerts that are currently active",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "namespace=~\"$namespace\",severity=~\"critical\"",
     "filters": "namespace=~$namespace,container=~\"$container\"",
     "labelSelector": "alertname, summary, description, message,job,namespace",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Active alerts by name",
   "type": "timeseries",
   "description": "Alerts that are currently active by alert name",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(ALERTS{cluster=~\"$cluster\",namespace=~\"$namespace\",alertname!=\"Watchdog\",container=~\"$container\"}) by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "Active Alerts by container",
   "type": "timeseries",
   "description": "Alerts that are currently active by container",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(ALERTS{cluster=~\"$cluster\",namespace=~\"$namespace\",instance=~\"$instance\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Notification Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(alertmanager_notifications_total{cluster=~\"$cluster\",instance=~\"$instance\"}[5m])) by (integration) > 0",
     "legendFormat": "{{integration}}"
    }
   ]
  }
 ]
}