{
 "title": "Hiero / Mirror / Importer",
 "tags": [
  "hiero",
  "mirror",
  "application",
  "importer"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "query": "importer" },
   { "name": "loki", "label": "Loki", "query": "loki" },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(system_cpu_count{application=\"$application\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(system_cpu_count{application=\"$application\",cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(system_cpu_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": {
     "query": "label_values(hiero_mirror_importer_parse_duration_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}, type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ready Pods",
   "type": "stat",
   "description": "The number of pods that are up and ready for processing",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(application_ready_time_seconds{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "description": "The average number of overall transactions per second",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hiero_mirror_importer_transaction_latency_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Transaction Size",
   "type": "stat",
   "description": "The average transaction size",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hiero_mirror_importer_transaction_size_bytes_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) / sum(hiero_mirror_importer_transaction_size_bytes_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Record Parse Duration",
   "type": "stat",
   "description": "The amount of time it took to successfully parse the record file",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hiero_mirror_importer_parse_duration_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",type=~\"RECORD\",success=\"true\"}[$__rate_interval])) / sum(rate(hiero_mirror_importer_parse_duration_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",type=\"RECORD\",success=\"true\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Record Parse Latency",
   "type": "stat",
   "description": "The difference in the consensus time of the last transaction in the file and the time at which the file was processed successfully",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hiero_mirror_importer_parse_latency_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"RECORD\"}[$__rate_interval])) / sum(rate(hiero_mirror_importer_parse_latency_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"RECORD\"}[$__rate_interval])) > 0"
    }
   ]
  },
  {
   "title": "Balance Parse Duration",
   "type": "stat",
   "description": "Amount of time it took to successfully parse the balance file",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hiero_mirror_importer_parse_duration_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",type=~\"BALANCE\",success=\"true\"}[$__rate_interval])) / sum(rate(hiero_mirror_importer_parse_duration_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",type=\"BALANCE\",success=\"true\"}[$__rate_interval])) > 0"
    }
   ]
  },
  {
   "title": "Uncompressed Database Size",
   "type": "stat",
   "description": "The uncompressed amount of storage used for the database. To see the compressed size, please see the ZFS dashboard.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_index_bytes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) + sum(db_table_bytes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transaction Rate",
   "type": "timeseries",
   "description": "The transactions per second broken down by type",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hiero_mirror_importer_transaction_latency_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(hiero_mirror_importer_transaction_latency_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (type) > 0",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Transaction Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(hiero_mirror_importer_transaction_size_bytes_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) / sum(rate(hiero_mirror_importer_transaction_size_bytes_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "(sum(rate(hiero_mirror_importer_transaction_size_bytes_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (type) / sum(rate(hiero_mirror_importer_transaction_size_bytes_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (type)) > 0",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Publish Duration",
   "type": "timeseries",
   "description": "The amount of time it took to publish the domain entity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(hiero_mirror_importer_publish_duration_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (type) / sum(rate(hiero_mirror_importer_publish_duration_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (type) > 0",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "The amount of memory consumed by the application",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(jvm_memory_committed_bytes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) > 0",
     "legendFormat": "committed"
    },
    {
     "expr": "avg(jvm_memory_used_bytes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) > 0",
     "legendFormat": "used"
    },
    {
     "expr": "avg(jvm_memory_max_bytes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) > 0",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "The amount of CPU consumed by the application",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(system_cpu_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "cores"
    },
    {
     "expr": "sum(process_cpu_usage{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"} * system_cpu_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "The number of threads in use by the JVM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(jvm_threads_states_threads{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (state) > 0",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "description": "The rate of HTTP requests received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (method, uri) > 0",
     "legendFormat": "{{ method}} {{uri}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "description": "The number of open file descriptors used by the process",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(process_files_max_files{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(process_files_open_files{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "open"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Table Rows",
   "type": "timeseries",
   "description": "The number of rows per table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(db_table_rows{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (table) > 0",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "timeseries",
   "description": "The size of the table and indexes on disk",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(db_table_bytes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (table) + sum(db_index_bytes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (table) > 0",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Table Size",
   "type": "timeseries",
   "description": "The size of the table on disk",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(db_table_bytes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (table) > 0",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "timeseries",
   "description": "The size of the indexes on disk",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(db_index_bytes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (table) > 0",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Database Operations",
   "type": "timeseries",
   "description": "The number of queries per second executed by the database",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(postgres_rows_fetched_total{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) > 0",
     "legendFormat": "selected"
    },
    {
     "expr": "sum(rate(postgres_rows_inserted_total{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) > 0",
     "legendFormat": "inserted"
    },
    {
     "expr": "sum(rate(postgres_rows_deleted_total{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) > 0",
     "legendFormat": "deleted"
    },
    {
     "expr": "sum(rate(postgres_rows_updated_total{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) > 0",
     "legendFormat": "updated"
    }
   ]
  },
  {
   "title": "Batch Insert Latency",
   "type": "timeseries",
   "description": "The time it took to batch insert rows",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(hiero_mirror_importer_batch_latency_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (table) / sum(rate(hiero_mirror_importer_batch_latency_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (table)) > 0",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Batch Insert Rows",
   "type": "timeseries",
   "description": "The number of rows inserted into the table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hiero_mirror_importer_batch_rows_total{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (table) > 0",
     "legendFormat": "{{ table }}"
    },
    {
     "expr": "sum(rate(hiero_mirror_importer_batch_rows_total{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "description": "The amount of time it takes to invoke the Spring Data repository method to execute a query.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(spring_data_repository_invocations_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (repository, method) / sum(rate(spring_data_repository_invocations_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (repository, method) > 0",
     "legendFormat": "{{repository}}::{{ method }}"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "timeseries",
   "description": "The number of database connections in the pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(hikaricp_connections_active{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) > 0",
     "legendFormat": "active"
    },
    {
     "expr": "avg(hikaricp_connections_idle{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) > 0",
     "legendFormat": "idle"
    },
    {
     "expr": "avg(hikaricp_connections_max{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) > 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(hikaricp_connections_pending{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) > 0",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "JDBC Connections",
   "type": "timeseries",
   "description": "The number of database connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(jdbc_connections_active{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) > 0",
     "legendFormat": "active"
    },
    {
     "expr": "avg(jdbc_connections_idle{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) > 0",
     "legendFormat": "idle"
    },
    {
     "expr": "avg(jdbc_connections_max{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) > 0",
     "legendFormat": "max"
    },
    {
     "expr": "avg(jdbc_connections_min{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) > 0",
     "legendFormat": "min"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Cache Hit",
   "type": "timeseries",
   "description": "The percent of time the value is retrieved from the cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (cache_gets_total{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",result=\"hit\"}) by (cache_manager, cache) / sum (cache_gets_total{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (cache_manager, cache)",
     "legendFormat": "{{ cache_manager }}.{{ cache }}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "description": "The number of entries in the cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(cache_size{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (cache_manager, cache)",
     "legendFormat": "{{ cache_manager }}.{{ cache }}"
    }
   ]
  },
  {
   "title": "Cache Get Rate",
   "type": "timeseries",
   "description": "The number of cache gets per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(cache_gets_total{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (cache_manager, cache)",
     "legendFormat": "{{ cache_manager }}.{{ cache }}"
    }
   ]
  },
  {
   "title": "Cache Put Rate",
   "type": "timeseries",
   "description": "The number of cache puts per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(cache_puts_total{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (cache_manager, cache)",
     "legendFormat": "{{ cache_manager }}.{{ cache }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "The rate of log events written by the application",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(logback_events_total{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (level) > 0",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "logs",
   "description": "The log events",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 154 },
   "targets": [
    {
     "expr": "{component=\"importer\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "$stream Stream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 },
   "repeat": "stream",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Stream List Rate",
     "type": "timeseries",
     "description": "The rate at which it the importer polls cloud storage for stream files",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_request_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"list\"}[$__rate_interval])) by (status) > 0",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Stream Download Latency",
     "type": "timeseries",
     "description": "How long it took to search for new stream files from cloud storage",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_request_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", status=~\"^2.*\"}[$__rate_interval])) by (action) / sum(rate(hiero_mirror_importer_stream_request_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", status=~\"^2.*\"}[$__rate_interval])) by (action) > 0",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Download Stream Signature Rate",
     "type": "timeseries",
     "description": "The rate at which it the importer downloads stream file signatures from cloud storage",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_request_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (node) > 0",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Download Stream Signature Latency",
     "type": "timeseries",
     "description": "How long it took to download the signature file from cloud storage",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 189 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_request_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (node) / sum(rate(hiero_mirror_importer_stream_request_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (node) > 0",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Download Stream File Rate",
     "type": "timeseries",
     "description": "The rate at which it the importer downloads stream files from cloud storage",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_request_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (node) > 0",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Download Stream File Latency",
     "type": "timeseries",
     "description": "How long it took to download stream files from cloud storage",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_request_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (node) / sum(rate(hiero_mirror_importer_stream_request_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (node) > 0",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Download Stream File Size",
     "type": "timeseries",
     "description": "The average stream file size",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 213 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_response_bytes_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (node) / sum(rate(hiero_mirror_importer_stream_response_bytes_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (node) > 0",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Download Signature File Size",
     "type": "timeseries",
     "description": "The average stream signature file size",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 221 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_response_bytes_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (node) / sum(rate(hiero_mirror_importer_stream_response_bytes_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (node) > 0",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Stream List Size",
     "type": "timeseries",
     "description": "The average file size of the stream list response from cloud storage",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 229 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_response_bytes_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"list\", status=~\"^2.*\"}[$__rate_interval])) by (node) / sum(rate(hiero_mirror_importer_stream_response_bytes_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"list\", status=~\"^2.*\"}[$__rate_interval])) by (node) > 0",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Signature Verification Rate",
     "type": "timeseries",
     "description": "The rate at which different node's signatures reach consensus",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 237 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_signature_verification_total{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", status=\"CONSENSUS_REACHED\"}[$__rate_interval])) by (node) > 0",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Stream File Verification Rate",
     "type": "timeseries",
     "description": "The rate at which the stream file reaches consensus, hash chain verified (if applicable) and hash matches signature",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 245 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_verification_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\"}[$__rate_interval])) by (success) > 0",
       "legendFormat": "success={{success}}"
      }
     ]
    },
    {
     "title": "Stream File Verification Latency",
     "type": "timeseries",
     "description": "The duration in seconds it took to reach consensus,  verify hash chain (if applicable) and hash matches the signature.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 253 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_verification_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=\"$stream\"}[$__rate_interval])) by (success) / sum(rate(hiero_mirror_importer_stream_verification_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=\"$stream\"}[$__rate_interval])) by (success) > 0",
       "legendFormat": "success={{success}}"
      }
     ]
    },
    {
     "title": "Cloud Storage Error Rate",
     "type": "timeseries",
     "description": "HTTP errors interacting with cloud storage",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 261 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_request_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", status!~\"^2.*\"}[$__rate_interval])) by (status, action) > 0",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Stream File Close Interval",
     "type": "timeseries",
     "description": "The difference between the consensus time of the last and first transaction in the stream file",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 269 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_close_latency_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) / sum(rate(hiero_mirror_importer_stream_close_latency_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) > 0",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "Stream Parse Duration",
     "type": "timeseries",
     "description": "The duration in seconds it took to parse the file and store it in the database",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 277 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_parse_duration_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) by (success) / sum(rate(hiero_mirror_importer_parse_duration_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\",type=\"$stream\"}[$__rate_interval])) by (success) > 0",
       "legendFormat": "success: {{success}}"
      }
     ]
    },
    {
     "title": "Cloud Storage Latency",
     "type": "timeseries",
     "description": "The difference in time between the consensus time of the last transaction in the file and the time at which the file was created in the cloud storage provider",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 285 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_cloud_latency_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) > 0 / sum(rate(hiero_mirror_importer_cloud_latency_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) > 0",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "Download Latency",
     "type": "timeseries",
     "description": "The difference in time between the consensus time of the last transaction in the file and the time at which the file was downloaded and verified",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 293 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_stream_latency_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) > 0 / sum(rate(hiero_mirror_importer_stream_latency_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) > 0",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "Parser Latency",
     "type": "timeseries",
     "description": "The difference in the consensus time of the last transaction in the file and the time at which the file was processed successfully",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 301 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_parse_latency_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) > 0 / sum(rate(hiero_mirror_importer_parse_latency_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) > 0",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "Total Duration",
     "type": "timeseries",
     "description": "The overall amount of time the importer took to process a stream file",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 309 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(hiero_mirror_importer_duration_seconds_sum{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) > 0 / sum(rate(hiero_mirror_importer_duration_seconds_count{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) > 0",
       "legendFormat": " "
      }
     ]
    }
   ]
  }
 ]
}