{
 "title": "JVM (Micrometer)",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(jvm_memory_used_bytes, application)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\",cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_start_time_seconds{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"} * 1000)"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Web Container Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_busy_threads{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "TOMCAT - BSY"
    },
    {
     "expr": "tomcat_threads_current_threads{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "TOMCAT - CUR"
    },
    {
     "expr": "tomcat_threads_config_max_threads{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "TOMCAT - MAX"
    },
    {
     "expr": "jetty_threads_busy{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JETTY - BSY"
    },
    {
     "expr": "jetty_threads_current{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JETTY - CUR"
    },
    {
     "expr": "jetty_threads_config_max{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JETTY - MAX"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_memory_vss_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "vss"
    },
    {
     "expr": "sum(process_memory_rss_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(process_memory_swap_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "swap"
    },
    {
     "expr": "sum(process_memory_rss_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"} + process_memory_swap_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(system_cpu_usage{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "system"
    },
    {
     "expr": "sum(process_cpu_usage{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "process"
    },
    {
     "expr": "sum(avg_over_time(process_cpu_usage{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}[1h]))",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(system_load_average_1m{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "load"
    },
    {
     "expr": "avg(system_cpu_count{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "CPUs"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "live"
    },
    {
     "expr": "sum(jvm_threads_daemon_threads{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "daemon"
    },
    {
     "expr": "sum(jvm_threads_peak_threads{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "peak"
    },
    {
     "expr": "sum(process_threads{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_states_threads{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(logback_events_total{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}[5m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_files_open_files{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "open"
    },
    {
     "expr": "sum(process_files_max_files{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "persistence_counts" },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Collections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}[1m])) by (action, cause)",
     "legendFormat": "{{action}}/{{cause}}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}[1m])/rate(jvm_gc_pause_seconds_count{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}[1m])) by (action, cause)",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "sum(jvm_gc_pause_seconds_max{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}) by (action, cause)",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}[1m]))",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}[1m]))",
     "legendFormat": "promoted"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_classes_loaded_classes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(jvm_classes_loaded_classes{application=\"$application\",cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\"}[1m]))",
     "legendFormat": "delta-1m"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_buffer_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=\"direct\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_buffer_total_capacity_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=\"direct\"})",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_buffer_count_buffers{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=\"direct\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_buffer_memory_used_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=\"mapped\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_buffer_total_capacity_bytes{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=\"mapped\"})",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_buffer_count_buffers{application=\"$application\", cluster=~\"$cluster\",namespace=~\"$namespace\",pod=\"$pod\", id=\"mapped\"})",
     "legendFormat": "count"
    }
   ]
  }
 ]
}