{
 "title": "PostgreSQL",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(system_cpu_count,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(pg_up{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(pg_exporter_last_scrape_duration_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"},pod)"
    }
   },
   { "name": "database", "query": "mirror_node" },
   { "name": "loki", "label": "Loki", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Query Latency",
   "type": "stat",
   "description": "The average query duration",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pgbouncer_show_stats_avg_query_time{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "stat",
   "description": "Number of queries per second",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pgbouncer_show_stats_total_query_count{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Clients",
   "type": "stat",
   "description": "Total number of active pg bouncer client connections",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer_show_pools_cl_active{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch",
   "type": "stat",
   "description": "Total fetched tuples from the database",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Insert",
   "type": "stat",
   "description": "Total inserted tuples in the database",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "description": "Total updated tuples in the database",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_updated_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Pool Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "PG bouncer active client and server connections",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pgbouncer_show_pools_cl_active{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"} != 0) by (user, pool_mode)",
     "legendFormat": "{{pool_mode}}-{{user}}-client"
    },
    {
     "expr": "sum(pgbouncer_show_pools_sv_active{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"} != 0) by (user, pool_mode)",
     "legendFormat": "{{pool_mode}}-{{user}}-server"
    },
    {
     "expr": "sum(pgbouncer_show_pools_cl_active{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"} != 0)",
     "legendFormat": "Total Client"
    },
    {
     "expr": "sum(pgbouncer_show_pools_sv_active{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"} != 0)",
     "legendFormat": "Total Server"
    }
   ]
  },
  {
   "title": "Waiting Connections",
   "type": "timeseries",
   "description": "PG bouncer waiting client connections",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pgbouncer_show_pools_cl_waiting{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (user, pool_mode)",
     "legendFormat": "{{pool_mode}}-{{user}}"
    },
    {
     "expr": "sum(pgbouncer_show_pools_cl_waiting{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "timeseries",
   "description": "PG bouncer idle server connections",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pgbouncer_show_pools_sv_idle{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"} != 0) by (user, pool_mode)",
     "legendFormat": "{{pool_mode}}-{{user}}"
    },
    {
     "expr": "sum(pgbouncer_show_pools_sv_idle{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"} != 0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Connection Bind",
   "type": "timeseries",
   "description": "PG bouncer bind connection count",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pgbouncer_show_stats_total_bind_count{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (database)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Client Assignment",
   "type": "timeseries",
   "description": "PG bouncer connection assignment count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pgbouncer_show_stats_total_server_assignment_count{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (database)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "description": "PG bouncer queries per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pgbouncer_show_stats_total_query_count{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (database)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Statement Parse Count",
   "type": "timeseries",
   "description": "PG bouncer prepared statement parse count",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pgbouncer_show_stats_total_server_parse_count{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (database)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Average Query Time",
   "type": "timeseries",
   "description": "Average query time for PG bouncer pool connections",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(pgbouncer_show_stats_avg_query_time{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (database)",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "PG bouncer total transferred/received bytes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(pgbouncer_show_stats_total_received{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(irate(pgbouncer_show_stats_total_sent{cluster=~\"$cluster\", database=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "sent"
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "Transaction commit/rollback count",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "commits"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) != 0)",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "timeseries",
   "description": "Count of buffer writes by backends, background writer, and checkpoints, and new buffer allocations",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_backend_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_alloc_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_checkpoint_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_clean_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "description": "Count of conflicts and deadlocks",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_conflicts_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "conflicts"
    },
    {
     "expr": "sum(irate(pg_stat_database_deadlocks_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "deadlocks"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "description": "Count of active locks broken down by lock type",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_locks_count{cluster=~\"$cluster\", datname=~\"$database\",  namespace=~\"$namespace\",  pod=~\"$pod\"} != 0) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "description": "Time spent writing buffers to disk",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_bgwriter_checkpoint_write_time_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_checkpoint_sync_time_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "sync"
    }
   ]
  },
  {
   "title": "Temp File (Bytes) Per Second",
   "type": "timeseries",
   "description": "Bytes of data written to temporary files by queries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_temp_bytes_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "timeseries",
   "description": "Total fetched tuples from the database",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched_total{cluster=~\"$cluster\", datname=~\"$database\",  namespace=~\"$namespace\",  pod=~\"$pod\"}[$__rate_interval])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "timeseries",
   "description": "Total returned tuples from the database",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_returned_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "timeseries",
   "description": "Total inserted tuples in the database",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "timeseries",
   "description": "Total updated tuples in the database",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_updated_total{cluster=~\"$cluster\", datname=~\"$database\",  namespace=~\"$namespace\",  pod=~\"$pod\"}[$__rate_interval])) by (datname)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "timeseries",
   "description": "Total deleted tuples from the database",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_deleted_total{cluster=~\"$cluster\", datname=~\"$database\",  namespace=~\"$namespace\",  pod=~\"$pod\"}[$__rate_interval])) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "description": "Percentage of disk blocks accessed directly from shared_buffer cache",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(pg_stat_database_blks_hit_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}/ (pg_stat_database_blks_read_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"}+ pg_stat_database_blks_hit_total{cluster=~\"$cluster\", datname=~\"$database\", namespace=~\"$namespace\", pod=~\"$pod\"})) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "the number of seconds replica is behind the leader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(sum(pg_replication_lag{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (cluster, namespace, pod))",
     "legendFormat": "lag"
    }
   ]
  },
  {
   "title": "Replication Lag Size",
   "type": "timeseries",
   "description": "the size, in bytes, replica is behind the leader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(sum(pg_replication_status_lag_size{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (cluster, namespace, pod))",
     "legendFormat": "lag"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "The rate of log events written by the database",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} !~ \"WARNING|ERROR\" [$__interval]))",
     "legendFormat": "info"
    },
    {
     "direction": "backward",
     "expr": "sum(rate({cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} |= \"WARNING\" [$__interval]))",
     "legendFormat": "warn"
    },
    {
     "direction": "backward",
     "expr": "sum(rate({cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"} |= \"ERROR\" [$__interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "logs",
   "description": "The log events",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 123 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  }
 ]
}