{
 "title": "PostgreSQL / Detail",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(pg_exporter_last_scrape_duration_seconds,pod)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(system_cpu_count,cluster)"
    }
   },
   { "name": "db", "query": "mirror_node" }
  ]
 },
 "panels": [
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched_total{cluster=~\"$cluster\", datname=~\"$db\", pod=~\"$pod\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted_total{cluster=~\"$cluster\", datname=~\"$db\", pod=~\"$pod\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_updated_total{cluster=~\"$cluster\", datname=~\"$db\", pod=~\"$pod\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Pool Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pgbouncer_show_pools_cl_active{cluster=~\"$cluster\", pod=~\"$pod\", database=\"$db\"} != 0",
     "legendFormat": "{{pod}}-{{pool_mode}}-{{user}}-client"
    },
    {
     "expr": "pgbouncer_show_pools_sv_active{cluster=~\"$cluster\", pod=~\"$pod\", database=\"$db\"} != 0",
     "legendFormat": "{{pod}}-{{pool_mode}}-{{user}}-server"
    }
   ]
  },
  {
   "title": "Waiting Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pgbouncer_show_pools_cl_waiting{cluster=~\"$cluster\", pod=~\"$pod\", database=~\"$db\"}",
     "legendFormat": "{{pod}}-{{pool_mode}}-{{user}}"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pgbouncer_show_pools_sv_idle{cluster=~\"$cluster\", pod=~\"$pod\", database=\"$db\"} != 0",
     "legendFormat": "{{pod}}-{{pool_mode}}-{{user}}"
    }
   ]
  },
  {
   "title": "Average Query Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "pgbouncer_show_stats_avg_query_time{cluster=~\"$cluster\", pod=~\"$pod\", database=~\"$db\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "irate(pgbouncer_show_stats_total_query_count{cluster=~\"$cluster\", pod=~\"$pod\", database=~\"$db\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(pgbouncer_show_stats_total_received{cluster=~\"$cluster\", pod=~\"$pod\", database=~\"$db\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-received"
    },
    {
     "expr": "irate(pgbouncer_show_stats_total_sent{cluster=~\"$cluster\", pod=~\"$pod\", database=~\"$db\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-sent"
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts_total{cluster=~\"$cluster\", pod=~\"$pod\", datname=~\"$db\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks_total{cluster=~\"$cluster\", pod=~\"$pod\", datname=~\"$db\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-deadlocks"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes_total{cluster=~\"$cluster\", pod=~\"$pod\", datname=~\"$db\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit_total{cluster=~\"\", pod=~\"$pod\", datname=~\"$db\"}[$__rate_interval]) ",
     "legendFormat": "{{pod}}-commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback_total{cluster=~\"\", pod=~\"$pod\", datname=~\"$db\"}[$__rate_interval]) != 0",
     "legendFormat": "{{pod}}-rollbacks"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-write"
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-sync"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean_total{cluster=~\"$cluster\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-buffers_clean"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_locks_count{datname=~\"$db\", pod=~\"$pod\"} != 0",
     "legendFormat": "{{pod}}-{{mode}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_inserted_total{cluster=~\"$cluster\", datname=~\"$db\", pod=~\"$pod\"}[$__rate_interval]) != 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_fetched_total{cluster=~\"$cluster\", datname=~\"$db\", pod=~\"$pod\"}[$__rate_interval]) != 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_returned_total{cluster=~\"$cluster\", datname=~\"$db\", pod=~\"$pod\"}[$__rate_interval]) != 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_updated_total{cluster=~\"$cluster\", datname=~\"$db\", pod=~\"$pod\"}[$__rate_interval]) != 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_deleted_total{cluster=~\"$cluster\", datname=~\"$db\", pod=~\"$pod\"}[$__rate_interval]) != 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit_total{cluster=~\"$cluster\", pod=~\"$pod\", datname=~\"$db\"} / (pg_stat_database_blks_read_total{cluster=~\"$cluster\", pod=~\"$pod\", datname=~\"$db\"} + pg_stat_database_blks_hit_total{cluster=~\"$cluster\", pod=~\"$pod\", datname=~\"$db\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}