{
 "title": "Traefik",
 "description": "Traefik dashboard prometheus",
 "tags": [ "traefik" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "loki", "label": "Loki", "query": "loki" },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(traefik_config_reloads_total, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(traefik_config_reloads_total{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(traefik_config_reloads_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traefik_service_requests_total{cluster=~\"$cluster\",namespace=~\"$namespace\"},service)"
    }
   },
   { "name": "percentiles", "query": "95,99" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "description": "The number of Traefik instances running",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_config_reloads_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Global latency ${percentiles}th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",code=~\"2..\"}[$__rate_interval])) by (le))",
     "legendFormat": "Latency over 5 min"
    }
   ]
  },
  {
   "title": "Per node latency ${percentiles}th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentiles, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",code=~\"2..\"}[$__rate_interval])) by (instance, le))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Entrypoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}) by (entrypoint)",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(rate(traefik_entrypoint_request_duration_seconds_bucket{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",le=\"0.1\",code=\"200\"}[$__rate_interval])) by (job) + sum(rate(traefik_entrypoint_request_duration_seconds_bucket{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",le=\"0.3\",code=\"200\"}[$__rate_interval])) by (job)) / 2 / sum(rate(traefik_entrypoint_request_duration_seconds_count{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",code=\"200\"}[$__rate_interval])) by (job)",
     "legendFormat": "Code 200"
    }
   ]
  },
  {
   "title": "Entrypoint Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (entrypoint)",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",service=~\"$service\"}) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(rate(traefik_service_request_duration_seconds_bucket{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",le=\"0.1\",code=~\"2.+\",service=~\"$service\"}[$__rate_interval])) by (job) + sum(rate(traefik_service_request_duration_seconds_bucket{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",le=\"0.3\",code=~\"2.+\",service=~\"$service\"}[$__rate_interval])) by (job)) / 2 / sum(rate(traefik_service_request_duration_seconds_count{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",code=~\"2.+\",service=~\"$service\"}[$__rate_interval])) by (job)",
     "legendFormat": "Code 200"
    }
   ]
  },
  {
   "title": "Service Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",service=~\"$service\"}[$__rate_interval])) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "HTTP Codes stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status Codes per Method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",service=~\"$service\"}[$__rate_interval])) by (method, code) > 0",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Status Codes by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",service=~\"$service\"}[$__rate_interval])) by (service, code)",
     "legendFormat": "{{service}} ({{code}})"
    }
   ]
  },
  {
   "title": "Pods resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traefik memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Memory used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",unit=\"byte\"})",
     "legendFormat": "Requested memory"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",unit=\"byte\"})",
     "legendFormat": "Limit memory usage"
    }
   ]
  },
  {
   "title": "Traefik CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Cpu used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",unit=\"core\"})",
     "legendFormat": "Requested cpu"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",namespace=\"$namespace\",pod=~\"$pod\",unit=\"core\"})",
     "legendFormat": "Limit cpu usage"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(rate({cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__interval]))",
     "legendFormat": " all"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "{cluster=~\"$cluster\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  }
 ]
}