{
 "title": "ZFS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "zfsDeviceId", "query": "sdb" },
   { "name": "loki", "label": "Loki", "query": "loki" },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(system_cpu_count,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\",node=~\"$node\"},namespace)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_zfs_arc_size{cluster=~\"$cluster\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "PVC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZPool IOps",
   "type": "timeseries",
   "description": "Number of read/write operations per ZFS dataset",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_dataset_reads{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) > 0",
     "legendFormat": "reads/{{dataset}}"
    },
    {
     "expr": "irate(node_zfs_zpool_dataset_writes{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) > 0",
     "legendFormat": "writes/{{dataset}}"
    }
   ]
  },
  {
   "title": "PVC Usage",
   "type": "timeseries",
   "description": "Percentage of used space",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", node=~\"$node\", namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\", node=~\"$node\", namespace=~\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC Size",
   "type": "timeseries",
   "description": "Used bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=~\"$cluster\", node=~\"$node\", namespace=~\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Waiting IO Requests",
   "type": "timeseries",
   "description": "Number of operations waiting to be serviced",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{cluster=~\"$cluster\", node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) >= 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Time taken for reads and writes",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{cluster=~\"$cluster\", node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{cluster=~\"$cluster\", node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) >= 0",
     "legendFormat": "read/{{node}}"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{cluster=~\"$cluster\", node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) >= 0",
     "legendFormat": "write/{{node}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "timeseries",
   "description": "Percentage of disk utilization",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{cluster=~\"$cluster\", node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) >= 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Bytes read/written",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{cluster=~\"$cluster\", node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) > 0",
     "legendFormat": "read/{{node}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{cluster=~\"$cluster\", node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) > 0",
     "legendFormat": "write/{{node}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "description": "Number of read/write operations",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{cluster=~\"$cluster\", node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) > 0",
     "legendFormat": "reads/{{node}}"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{cluster=~\"$cluster\", node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) > 0",
     "legendFormat": "write/{{node}}"
    }
   ]
  },
  { "title": "ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Hits / Miss Rate",
   "type": "timeseries",
   "description": "Per cache type rate data is found/missed in the ARC",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) > 0",
     "legendFormat": "data-hits/{{node}}"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) > 0",
     "legendFormat": "metadata-hits/{{node}}"
    },
    {
     "expr": "irate(node_zfs_arc_demand_data_misses{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) > 0",
     "legendFormat": "data-misses/{{node}}"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_misses{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) > 0",
     "legendFormat": "metadata-misses/{{node}}"
    }
   ]
  },
  {
   "title": "ARC HIT %",
   "type": "timeseries",
   "description": "Per cache type hit percentage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(irate(node_zfs_arc_demand_data_hits{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) / (irate(node_zfs_arc_demand_data_hits{cluster=~\"$cluster\",  node=~\"$node\"}[$__rate_interval]) + irate(node_zfs_arc_demand_data_misses{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]))) >= 0",
     "legendFormat": "data/{{node}}"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) / (irate(node_zfs_arc_demand_metadata_hits{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) + irate(node_zfs_arc_demand_metadata_misses{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval])) >= 0",
     "legendFormat": "metadata/{{node}}"
    }
   ]
  },
  {
   "title": "ARC BreakDown",
   "type": "timeseries",
   "description": "Per cache type used bytes ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{cluster=~\"$cluster\", node=~\"$node\"} > 0",
     "legendFormat": "data/{{node}}"
    },
    {
     "expr": "node_zfs_arc_metadata_size{cluster=~\"$cluster\", node=~\"$node\"} > 0",
     "legendFormat": "metadata/{{node}}"
    },
    {
     "expr": "node_zfs_arc_anon_size{cluster=~\"$cluster\", node=~\"$node\"} > 0",
     "legendFormat": "anon/{{node}}"
    },
    {
     "expr": "node_zfs_arc_hdr_size{cluster=~\"$cluster\", node=~\"$node\"} > 0",
     "legendFormat": "hdr/{{node}}"
    },
    {
     "expr": "node_zfs_arc_overhead_size{cluster=~\"$cluster\", node=~\"$node\"} > 0",
     "legendFormat": "overhead/{{node}}"
    }
   ]
  },
  {
   "title": "ARC Compress Ratio",
   "type": "timeseries",
   "description": "Compression ratio of data currently in the ARC",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "node_zfs_arc_size{cluster=~\"$cluster\", node=~\"$node\"} / node_zfs_arc_compressed_size{cluster=~\"$cluster\", node=~\"$node\"} >= 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "L2 ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Size",
   "type": "timeseries",
   "description": "Used bytes of L2 cache",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_l2_asize{cluster=~\"$cluster\", node=~\"$node\"} > 0",
     "legendFormat": "asize/{{node}}"
    },
    {
     "expr": "node_zfs_arc_l2_hdr_size{cluster=~\"$cluster\", node=~\"$node\"} > 0",
     "legendFormat": "hdr/{{node}}"
    },
    {
     "expr": "node_zfs_arc_l2_size{cluster=~\"$cluster\", node=~\"$node\"} > 0",
     "legendFormat": "size/{{node}}"
    }
   ]
  },
  {
   "title": "Hit / Miss Rate",
   "type": "timeseries",
   "description": "The rate data is found/missed in cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) > 0",
     "legendFormat": "hits/{{node}}"
    },
    {
     "expr": "irate(node_zfs_arc_l2_misses{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) > 0",
     "legendFormat": "misses/{{node}}"
    }
   ]
  },
  {
   "title": "Hit %",
   "type": "timeseries",
   "description": "Percentage requested data is in L2 cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) / (irate(node_zfs_arc_l2_hits{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval]) + irate(node_zfs_arc_l2_misses{cluster=~\"$cluster\", node=~\"$node\"}[$__rate_interval])) > 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ZFS Node Messages",
   "type": "logs",
   "description": "The log events for ZFS nodes",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "{component=~\".*zfs-node.*\", cluster=\"$cluster\", node_name=~\"$node\"}"
    }
   ]
  },
  {
   "title": "ZFS Controller Messages",
   "type": "logs",
   "description": "The log events for ZFS controller",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "{component=~\".*zfs-controller.*\", cluster=\"$cluster\"}"
    }
   ]
  }
 ]
}