apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mirror
  namespace: integration-docker
spec:
  chart:
    spec:
      chart: hedera-mirror
      sourceRef:
        kind: HelmRepository
        name: hedera-mirror-node
      valuesFiles:
        - values.yaml
        - values-prod.yaml
      version: '0.128.0-rc1'
  dependsOn:
    - name: mirror
      namespace: common
  driftDetection:
    mode: warn
  install:
    crds: CreateReplace
  interval: 90s
  test:
    enable: true
    timeout: 20m
  timeout: 20m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: mirror
  values:
    global:
      env:
        HEDERA_MIRROR_COMMON_REALM: "1"
        HEDERA_MIRROR_COMMON_SHARD: "1"
    importer:
      env:
        HEDERA_MIRROR_IMPORTER_NETWORK: "OTHER"
        HEDERA_MIRROR_IMPORTER_PARSER_RECORD_SIDECAR_ENABLED: "true"
    monitor:
      env:
        HEDERA_MIRROR_MONITOR_NETWORK: "OTHER"
        HEDERA_MIRROR_MONITOR_PUBLISH_SCENARIOS_PINGER_TPS: "0.5"
      prometheusRules:
        MonitorPublishErrors:
          enabled: false
        MonitorPublishLatency:
          enabled: false
        MonitorSubscribeLatency:
          enabled: false
    postgresql:
      enabled: false
    rest:
      monitor:
        config:
          stateproof:
            enabled: false
    test:
      config:
        hedera:
          mirror:
            test:
              acceptance:
                network: OTHER
                web3:
                  modularizedServices: true
      enabled: true
    web3:
      env:
        HEDERA_MIRROR_WEB3_EVM_MODULARIZEDTRAFFICPERCENT: "1.0"
        HEDERA_MIRROR_WEB3_EVM_MODULARIZEDSERVICES: "true"
        HEDERA_MIRROR_WEB3_EVM_NETWORK: OTHER

