---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgBkTFKTnOuoOAaCDxm9t9n22lkPqUydxloC+Sf1LB+pvPffkDxTFOVo4cbSxMFV3lIjVz+ebaGHTmn8qu77/22KCAlF8XYz/9g7o+uXXTrg7DAcwlgSLM+T8Hk/SHcybvf9YIbIFjRtjU6y5v5pCxk1iDiSgd/dZTzlrjF9h3OLE0081SfQxGMJsSOfCusBfph7OekzpUojD1lt3NOKZXmFMRwtCj7fNsdG7CBcPcwCDT9qCJQMKX+AhvBIewnOBd0mxK0tXe87NOJZTEFC6LjuGd0jvJwi+/xa2LWKfWmML7LpU3rv91tyYO+6WfQ4Bo5VsAdYLQQbR/fxEMF5UVx5XyCKC+OsJH9znW+wGauENU6VvPZtQIndqzKhwuirEB5GNr2RKhITUTaBEZC2XEMaAsBqCKfrM/lF+Dr/B1lYjzh8AzcY6uJ9Ys4o4VNAF5RNsTtryk95VQxol87JgxOxK8gF8dblewW0w/EogpXrrVjVi+X0TR++cuuvYZw/GRKCx+9ewCoiSOnpnbmTJrToL6X4fUC0ECFRtofOw2G8y5AU2RZlpzQ6GXHWuXe1/7OQ2wxP53peFlnE/GoIRnboZ4P52lO2NyZUDA0ERTOHkh8ox6+rMYPJtan0YgppD/MmlzhS8l8syLzpyF8+wCabMGIrtWccFaTcLUENQjRmwkAqYp/axTCgxfqxwSaUgCxaUdmx5ALz7LT0OXj/hv59wfkcFVk4RiqUKZRu+eALHPAxEeEAKEeT6d/xROrI18Xx0dLz1ofKOG8VIMj6yfrRU4dWScdLjOPFoAlkKKliGuZeb3YQaaQQRqh02YyasI/B2ofrnVEZ9nqEVHj1+Offc5y3uKn41Fw=
    username: AgBkpyGB9RO5HO87BmsPVCWN0Oxoa+46V0mH9lHCFjKtGbrBYSKOUSpYZTe4/+BUj8OK1kDuZ8GHXeTab6srBiP6wLFpb9OfDh3HwrLH02sQYMBxr753Ex7cavQn3kD02P06DTzCJ46M5w/jRKpE4rr1xwmcHd4C6CZ6krXEb9pDaCAR3BBs+ofRpTZOIUfgG4SzDdOq+zZN1L2SpYZTI8vdCehR3Wn2E3rIwXB1v0XHhSI2KWYHQtYuJgzuGzkJlxaA1Ju8erXHSFYHGmRBXMJycNtQ2jFoo0wAng77valBYzLS2OhHl6ZZqSaNg62/q11jYhMP5QPV8amaaqtgy6rKqPD7oiibfbusKoowDxmgfb1eK0X3oWwUh26OHuw4E3r4WbzWMmBqDE4bB624hNdnZluY1vIxnmDmMrxafan9WVPDjnq6foM2+9bu0TivRGuqGuBF3D4Ed/dz0MoxwGCbInQMYMA3Q/TLQQcsvEvt+Hf3Rdoedwd9Ia0FOJ7GDBm2zurwrnMRzROYBPIFwsCFwoV0YQOkiIjPGgIYy49aqUevVwtQB3/xtaXAx/X8HohrQ4WQ8vuh3wMMUQcAIQb2m4qk9vThtkZRn3eK2vi/saV3tfrRxAFQHGU6C8F9qFGdaVTn2QUnaC+nfn3hsjfvrJeoi8saGB2bitc1ywFmbOMrK1QYs/LIbVANw8D/TQ7zQT7qA5A=
  template:
    metadata:
      name: grafana-cloud
      namespace: common
    type: Opaque
