---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mirror
  namespace: common
spec:
  encryptedData:
    values.yaml: AgAP+f6t+coKeX9c9eyiae1mQjHma63XJYaxpb6TKpzTV33HZi7DM9gVUsiy0TGmDDFxbRIKMmNyCTknG6FVR5Tambarv4oA3lfE75qfSdmw5dFDHrIK3d1p85ha3e0iTdlW46xUgd2ulx8wXG1Qyif1gjXXYO9aJ8ZEKYQt0m9hNkbq8Ljj8WtyNR2aRAFRDCu3TwzEa+rC8wj0IgotoLQHWgbgz504LD+v9Sn2aAmolmmKSQfnTi6OiVz6aFTIcZ9lmfKKWAG4ZUFnJEGqKrIe4kMiuVWd1mopLylXf36onpxXHxd6ZJGwF/a5viZkuDbt1I4fWn2Haq/nsdx4tRIJyZLrgbbgEA4K8GIGVIUK9iZMijkrDhPIuxNiLzzsuzA7G98yaTP/wudTXifvaX0GALj7D0WAYpBXMEdGkMCbOgj8Uz9G+zEOAFLAuFuoFdNhX/pHjR+UwgOH1ZQj38bQK0+KTcWlh68lunoxtuTZLIjGbYRHrsVMMFV4iY2E/JAyRNZAw/qWfSkihZxrB+9F+SA0m2lho369lTp+QPFXMmf3fFyp4H02WhJLoI0QltwqkIH4kkz93bdQaWWZwTNqHKiuY7Q324ZjeF3a7egefkVz2tasIf/g0iOYA6L8m1QTzsOniOIDkJNiddhafdRKBnNMLtl6tcUzT3fxGMaLLt/3HBMGGDbNZaYJh/G0V1pPlXLMlrsP0GZFUoObSqfB01Xa107H4nqyu6bX1TD9w7d76LktcG1nugKqdGY3kd8Tfugid7kKf4M8SQUfJBPl/baimO8O+6h0oQ3+1nFUNDhOV6W2QJIXZ/kIeH38zW9fekYrR3ZrFs6ySziL6FHYS4KoOK673yZ+/cHk4IPsN1oUQra6qS+0Kqae6dtil0KYIVhRTpO7pj5ZXn9fs6K3+3X6h+S3hZ2z/C+gpOS5WaskWRReRC93fiMe6fkS3rIwukriCBLF1hxNLCyyfzo3nO8gJC+tKYEKg4KOjsbBQpKkZUt6tkeErextOTr0USA4iGGEk6NWpUhAZ6Sq7985foZ0peGoh9bHiJH21pjhOUlEoIdofOjM4wDDoJdC5dt6iYAjKABP1GY1YhIdsMvaG6iCZxRcXw0o+FGIADaO0EmNVHEMvw==
  template:
    metadata:
      name: mirror
      namespace: common
    type: Opaque
