apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-dispatch
  namespace: flux-system
spec:
  address: https://github.com/hiero-ledger/hiero-mirror-node
  secretRef:
    name: github-dispatch-token
  type: githubdispatch

