description = "Custom Paketo builder for web3 with libsodium"

[[buildpacks]]
id = "paketo-buildpacks/java-native-image"
uri = "docker://docker.io/paketobuildpacks/java-native-image:latest"

[[buildpacks]]
id = "paketo-buildpacks/health-checker"
uri = "docker://docker.io/paketobuildpacks/health-checker:latest"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/java-native-image"

  [[order.group]]
    id = "paketo-buildpacks/health-checker"
    optional = true

[build]
image = "docker.io/jesseswirldslabs/web3-build-noble-libsodium:20260317-3"

[run]
  [[run.images]]
    image = "docker.io/jesseswirldslabs/web3-run-noble-libsodium:20260317-3"

[stack]
id = "io.buildpacks.stacks.noble"
build-image = "docker.io/jesseswirldslabs/web3-build-noble-libsodium:20260317-3"
run-image = "docker.io/jesseswirldslabs/web3-run-noble-libsodium:20260317-3"
