# SPDX-License-Identifier: Apache-2.0

{{ if .Values.ingress.enabled -}}
{{- $fullName := include "hedera-mirror-rest-java.fullname" $ -}}
{{- $hostname := .Values.global.hostname -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
  labels: {{ include "hedera-mirror-rest-java.labels" . | nindent 4 }}
  name: {{ $fullName }}
  namespace: {{ include "hedera-mirror-rest-java.namespace" . }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ $hostname | default .host | quote }}
    http:
      paths:
      {{- range .paths }}
        {{- $pathEnabled := false -}}
          {{- if eq .path "/api/v1/accounts/(\\d+\\.){0,2}(\\d+|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))/allowances/nfts" }}
            {{- $pathEnabled = $.Values.gateway.endpoints.accounts.allowances.nfts.enabled -}}
            {{- else if eq .path "/api/v1/accounts/(\\d+\\.){0,2}(\\d+|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))/airdrops/outstanding" }}
            {{- $pathEnabled = $.Values.gateway.endpoints.accounts.airdrops.outstanding.enabled -}}
            {{- else if eq .path "/api/v1/accounts/(\\d+\\.){0,2}(\\d+|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))/airdrops/pending" }}
            {{- $pathEnabled = $.Values.gateway.endpoints.accounts.airdrops.pending.enabled -}}
            {{- else if eq .path "/api/v1/topics/(\\d+\\.){0,2}\\d+$" }}
            {{- $pathEnabled = $.Values.gateway.endpoints.topics.enabled -}}
          {{- end }}
          {{- if $pathEnabled }}
            - path: {{ .path }}
              pathType: {{ .type | default "ImplementationSpecific" }}
              backend:
                service:
                  name: {{ $fullName }}
                  port:
                    number: {{ $servicePort }}
          {{- end }}
        {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
      {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
