# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "hedera-mirror-rest-java.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-rest-java.fullname" . }}
  namespace: {{ include "hedera-mirror-rest-java.namespace" . }}
type: Opaque
stringData:
  application.yaml: |-
    {{- toYaml (mergeOverwrite .Values.config .Values.global.config) | nindent 4 }}
