// SPDX-License-Identifier: Apache-2.0

package org.hiero.mirror.test.e2e.acceptance.util.env;

public enum K6EnvProperties {
    ACCOUNT_ADDRESS("ACCOUNT_ADDRESS"),
    ASSOCIATED_ACCOUNT("ASSOCIATED_ACCOUNT"),
    DEFAULT_CONTRACT_ADDRESS("DEFAULT_CONTRACT_ADDRESS"),
    ERC_CONTRACT_ADDRESS("ERC_CONTRACT_ADDRESS"),
    ESTIMATE_PRECOMPILE_CONTRACT("ESTIMATE_PRECOMPILE_CONTRACT"),
    FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ADDRESS("FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ADDRESS"),
    FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ASSOCIATED_ACCOUNT_ADDRESS(
            "FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ASSOCIATED_ACCOUNT_ADDRESS"),
    NON_FUNGIBLE_TOKEN_ADDRESS("NON_FUNGIBLE_TOKEN_ADDRESS"),
    NON_FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ADDRESS("NON_FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ADDRESS"),
    PAYER_ACCOUNT("PAYER_ACCOUNT"),
    PRECOMPILE_CONTRACT("PRECOMPILE_CONTRACT"),
    RECEIVER_ADDRESS("RECEIVER_ADDRESS"),
    SPENDER_ADDRESS("SPENDER_ADDRESS"),
    TOKEN_ADDRESS("TOKEN_ADDRESS"),
    TOKEN_FREEZE_KEY_ACCOUNT_ADDRESS("TOKEN_FREEZE_KEY_ACCOUNT_ADDRESS");

    K6EnvProperties(String name) {}
}
