# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "hedera-mirror-importer.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-importer.fullname" . }}
  namespace: {{ include "hedera-mirror-importer.namespace" . }}
type: Opaque
data:
  {{- $config := deepCopy .Values.config }}
  {{- if .Values.addressBook }}
  {{- $addressBookConfig := dict "hedera" (dict "mirror" (dict "importer" (dict "initialAddressBook" "/usr/etc/hiero/addressbook.bin" ))) }}
  {{- $config = merge $config $addressBookConfig }}
  addressbook.bin: {{ .Values.addressBook }}
  {{- end }}
  application.yaml: {{ toYaml (mergeOverwrite $config .Values.global.config) | b64enc }}
