# SPDX-License-Identifier: Apache-2.0

name: Deploy to Preprod Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: string
      version:
        description: "Version"
        required: true
        type: string

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  LC_ALL: C.UTF-8

jobs:
  deploy:
    name: Deploy
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      VERSION: ${{ github.event.inputs.version }}
    runs-on: hiero-mirror-node-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Validate environment
        run: |
          set -euo pipefail

          [[ ! "$ENVIRONMENT" =~ ^(common|integration|mainnet.*|previewnet.*|testnet.*)$ ]] || \
            { echo "Deploying to $ENVIRONMENT is not allowed" && false; }
          [[ "$ENVIRONMENT" = "performance" ]] && ENVIRONMENT="${ENVIRONMENT}-citus" || true
          echo ENVIRONMENT=${ENVIRONMENT} >> $$GITHUB_ENV

      - name: Validate version
        run: |
          set -euo pipefail

          VERSION=${VERSION#v}
          curl -fsSL -o /dev/null ${{ github.server_url }}/${{ github.repository }}/tree/"v$VERSION"
          echo VERSION=${VERSION} >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: deploy
          token: ${{ secrets.HEDERA_BOT_TOKEN }}

      - name: Install yq
        env:
          BINARY: yq_linux_amd64
          TARGET: /home/runner/.local/bin
          VERSION: v4.46.1
        run: |
          mkdir -p "${TARGET}"
          cd "${TARGET}"
          curl -sL https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz --output - | tar -xvz
          mv ${BINARY} yq

      - name: Update deployment version
        run: yq -i '.spec.chart.spec.version |= env(VERSION)' clusters/preprod/${ENVIRONMENT}/helmrelease.yaml

      - name: Import GPG Key
        id: gpg_importer
        uses: step-security/ghaction-import-gpg@c86c374c0659a6c2d1284bccf8af889e73ce8fe0 # v6.3.0
        with:
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Auto-Commit
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          commit_author: ${{ steps.gpg_importer.outputs.name }} <${{ steps.gpg_importer.outputs.email }}>
          commit_message: Deploy v${{ env.VERSION }} to ${{ env.ENVIRONMENT }}
          commit_options: "--no-verify --signoff"
          commit_user_email: ${{ steps.gpg_importer.outputs.email }}
          commit_user_name: ${{ steps.gpg_importer.outputs.name }}
