# SPDX-License-Identifier: Apache-2.0

name: GitHub Pages Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  sync:
    name: Sync Pages
    runs-on: hiero-mirror-node-linux-medium

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: "hashgraph/hedera-mirror-node"
          ref: gh-pages
          fetch-depth: "0"
          token: ${{ secrets.GH_ACCESS_TOKEN_HG }}

      - name: Add Remote
        run: git remote add HIERO https://github.com/hiero-ledger/hiero-mirror-node.git

      - name: Get the latest from HIERO
        run: git fetch HIERO

      - name: Sync gh-pages locally
        run: git rebase --merge HIERO/gh-pages

      - name: Push updates
        run: git push --force --set-upstream origin gh-pages
