name: GitHub Pages Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  sync:
    name: Sync Pages
    runs-on: hiero-mirror-node-linux-medium

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: gh-pages
          fetch-depth: "0"

      - name: Import GPG Key
        id: gpg_importer
        uses: step-security/ghaction-import-gpg@6c8fe4d0126a59d57c21f87c9ae5dd3451fa3cca # v6.1.0
        with:
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GH_PAGES_ACCESS_TOKEN }}
          passphrase: ${{ secrets.GH_PAGES_TOKEN_PASSWORD }}

      - name: Add Remote and Sync
        run: |
          git remote add HASHGRAPH git@github.com:hashgraph/hedera-mirror-node.git
          git fetch HASHGRAPH
          git push HASHGRAPH gh-pages
