name: GitHub Pages Sync
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  sync:
    name: Sync Pages
    runs-on: hiero-mirror-node-linux-medium

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: gh-pages
          fetch-depth: "0"

      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.SSH_ACCESS_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Add Remote
        run: git remote add HASHGRAPH git@github.com:hashgraph/hedera-mirror-node.git

      - name: Fetch from target branch
        run: git fetch HASHGRAPH

      - name: Sync target branch
        run: git push HASHGRAPH gh-pages
