# SPDX-License-Identifier: Apache-2.0

name: Consensus node release branches compare
on:
  pull_request:
    branches:
      - main
      - release/**
    paths:
      - "build.gradle.kts"
defaults:
  run:
    shell: bash
permissions:
  contents: read
env:
  LC_ALL: C.UTF-8
jobs:
  check-version:
    name: Check if hedera app version changed in the PR
    runs-on: hiero-mirror-node-linux-large
    outputs:
      changed: ${{ steps.check.outputs.changed }}
      pr_version: ${{ steps.check.outputs.pr_version }}
      base_version: ${{ steps.check.outputs.base_version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Compare versions
        id: check
        run: |
          set -ex

          PR_VERSION=$(grep -o 'api("com\.hedera\.hashgraph:app:[^"]*")' build.gradle.kts | sed -E 's/.*app:([^"]*)".*/\1/')
          PR_VERSION_TAG="v$PR_VERSION"

          git fetch origin ${{ github.base_ref }} --depth=1
          git show origin/${{ github.base_ref }}:build.gradle.kts > base_build.gradle.kts
          BASE_VERSION=$(grep -o 'api("com\.hedera\.hashgraph:app:[^"]*")' base_build.gradle.kts | sed -E 's/.*app:([^"]*)".*/\1/')
          BASE_VERSION_TAG="v$BASE_VERSION"

          echo "pr_version=$PR_VERSION_TAG" >> $GITHUB_OUTPUT
          echo "base_version=$BASE_VERSION_TAG" >> $GITHUB_OUTPUT

          if [ "$PR_VERSION_TAG" != "$BASE_VERSION_TAG" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  run-diff-script:
    name: Compare files of different releases
    runs-on: hiero-mirror-node-linux-large
    needs: check-version
    if: needs.check-version.outputs.changed == 'true'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4

      - name: Run diff script
        run: |
          set -ex

          CONSENSUS_NODE_REPO="https://github.com/hiero-ledger/hiero-consensus-node.git"

          FILES_TO_COMPARE=(
            "com/hedera/hapi/node/state/token/Account.java"
            "com/hedera/hapi/node/state/token/Token.java"
            "com/hedera/hapi/node/state/token/TokenRelation.java"
            "com/hedera/hapi/node/state/file/File.java"
            "com/hedera/hapi/node/state/schedule/Schedule.java"
            "com/swirlds/state/spi/ReadableKVStateBase.java"
            "com/swirlds/state/spi/WritableKVStateBase.java"
          )

          # Temp directories to store cloned repos
          TMP_DIR_ONE=$(mktemp -d)
          TMP_DIR_TWO=$(mktemp -d)

          TAG_ONE="${{ needs.check-version.outputs.pr_version }}"
          TAG_TWO="${{ needs.check-version.outputs.base_version }}"

          echo "Comparing consensus node release versions $TAG_ONE and $TAG_TWO ..."

          generate_pbj_source() {
            local tag="$1"
            local target_dir="$2"

            git clone --depth 1 --branch "$tag" "$CONSENSUS_NODE_REPO" "$target_dir" > /dev/null 2>&1
            cd "$target_dir"
            ./gradlew hapi:generatePbjSource > /dev/null 2>&1
            cd - > /dev/null
          }

          generate_pbj_source "$TAG_ONE" "$TMP_DIR_ONE"
          generate_pbj_source "$TAG_TWO" "$TMP_DIR_TWO"

          # Flag to track for differences
          CHANGED=false

          compare_file() {
            local input_file_path="$1"
            local branch_one_file_path branch_two_file_path

            if [[ "$input_file_path" == com/swirlds/* ]]; then
              branch_one_file_path="$TMP_DIR_ONE/platform-sdk/swirlds-state-api/src/main/java/$input_file_path"
              branch_two_file_path="$TMP_DIR_TWO/platform-sdk/swirlds-state-api/src/main/java/$input_file_path"
            else
              branch_one_file_path="$TMP_DIR_ONE/hapi/hapi/build/generated/source/pbj-proto/main/java/$input_file_path"
              branch_two_file_path="$TMP_DIR_TWO/hapi/hapi/build/generated/source/pbj-proto/main/java/$input_file_path"
            fi

            if ! diff_output=$(diff -u "$branch_two_file_path" "$branch_one_file_path"); then
              echo "File changed: $input_file_path"
              echo "----------------------------------------"
              echo "$diff_output"
              echo "----------------------------------------"
              CHANGED=true
            fi
          }

          for file in "${FILES_TO_COMPARE[@]}"; do
            compare_file "$file"
          done

          if [ "$CHANGED" = false ]; then
            echo "No differences detected between versions $TAG_TWO and $TAG_ONE for the specified set of files."
          else
            echo "Differences detected between versions $TAG_TWO and $TAG_ONE for the specified set of files."
            exit 1
          fi

        timeout-minutes: 30
