# SPDX-License-Identifier: Apache-2.0

name: Consensus node release branches compare
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/**
    paths:
      - "build.gradle.kts"
defaults:
  run:
    shell: bash
permissions:
  contents: read
env:
  LC_ALL: C.UTF-8
jobs:
  run-diff-script:
    name: Compare latest two releases of consensus node
    runs-on: hiero-mirror-node-linux-large
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check if hedera app version changed in the PR
        id: check-hedera-app-line
        run: |
          set -ex

          PR_VERSION=$(grep -o 'api("com\.hedera\.hashgraph:app:[^"]*")' build.gradle.kts | sed -E 's/.*app:([^"]*)".*/\1/')
          PR_VERSION_TAG="v$PR_VERSION"

          git fetch origin ${{ github.base_ref }} --depth=1
          git show origin/${{ github.base_ref }}:build.gradle.kts > base_build.gradle.kts
          BASE_VERSION=$(grep -o 'api("com\.hedera\.hashgraph:app:[^"]*")' base_build.gradle.kts | sed -E 's/.*app:([^"]*)".*/\1/')
          BASE_VERSION_TAG="v$BASE_VERSION"

          echo "pr_version=$PR_VERSION_TAG" >> $GITHUB_OUTPUT
          echo "base_version=$BASE_VERSION_TAG" >> $GITHUB_OUTPUT

          if [ "$PR_VERSION_TAG" != "$BASE_VERSION_TAG" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Install JDK
        if: steps.check-hedera-app-line.outputs.changed == 'true'
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        if: steps.check-hedera-app-line.outputs.changed == 'true'
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4

      - name: Run diff script
        if: steps.check-hedera-app-line.outputs.changed == 'true'
        run: |
          set -ex

          CONSENSUS_NODE_REPO="https://github.com/hiero-ledger/hiero-consensus-node.git"

          FILES_TO_COMPARE=(
            "com/hedera/hapi/node/state/token/Account.java"
            "com/hedera/hapi/node/state/token/Token.java"
            "com/hedera/hapi/node/state/token/TokenRelation.java"
            "com/hedera/hapi/node/state/file/File.java"
            "com/hedera/hapi/node/state/schedule/Schedule.java"
            "com/swirlds/state/spi/ReadableKVStateBase.java"
            "com/swirlds/state/spi/WritableKVStateBase.java"
          )

          # Temp directories to store cloned repos
          TMP_DIR_ONE=$(mktemp -d)
          TMP_DIR_TWO=$(mktemp -d)

          TAG_ONE="${{ steps.check-hedera-app-line.outputs.pr_version }}"
          TAG_TWO="${{ steps.check-hedera-app-line.outputs.base_version }}"

          echo "Comparing consensus node release versions $TAG_ONE and $TAG_TWO ..."

          git clone --depth 1 --branch "$TAG_ONE" "$CONSENSUS_NODE_REPO" "$TMP_DIR_ONE" > /dev/null 2>&1
          cd "$TMP_DIR_ONE"
          ./gradlew hapi:generatePbjSource > /dev/null 2>&1

          git clone --depth 1 --branch "$TAG_TWO" "$CONSENSUS_NODE_REPO" "$TMP_DIR_TWO" > /dev/null 2>&1
          cd "$TMP_DIR_TWO"
          ./gradlew hapi:generatePbjSource > /dev/null 2>&1

          # Flag to track for differences
          CHANGED=false

          compare_file() {
            local input_file_path="$1"
            local branch_one_file_path branch_two_file_path

            if [[ "$input_file_path" == com/swirlds/* ]]; then
              branch_one_file_path="$TMP_DIR_ONE/platform-sdk/swirlds-state-api/src/main/java/$input_file_path"
              branch_two_file_path="$TMP_DIR_TWO/platform-sdk/swirlds-state-api/src/main/java/$input_file_path"
            else
              branch_one_file_path="$TMP_DIR_ONE/hapi/hapi/build/generated/source/pbj-proto/main/java/$input_file_path"
              branch_two_file_path="$TMP_DIR_TWO/hapi/hapi/build/generated/source/pbj-proto/main/java/$input_file_path"
            fi

            if ! diff -q "$branch_one_file_path" "$branch_two_file_path" >/dev/null 2>&1; then
              echo "File changed: $input_file_path"
              echo "----------------------------------------"
              diff -u "$branch_two_file_path" "$branch_one_file_path" || true
              echo "----------------------------------------"
              CHANGED=true
            fi
          }

          for file in "${FILES_TO_COMPARE[@]}"; do
            compare_file "$file"
          done

          if [ "$CHANGED" = false ]; then
            echo "No file changes detected."
          else
            echo "Differences detected."
            exit 1
          fi

        timeout-minutes: 30
