# SPDX-License-Identifier: Apache-2.0

name: Rosetta API
on:
  schedule:
    - cron: "0 1 * * *" # Daily at 1:00 AM
  push:
    branches:
      - "main"
    tags:
      - "v*"

defaults:
  run:
    shell: bash
    working-directory: ./rosetta

permissions:
  contents: read

env:
  MODULE: rosetta
  NETWORK: previewnet

jobs:
  validate:
    runs-on: hiero-mirror-node-linux-large
    timeout-minutes: 30
    env:
      ROSETTA_CLI_VERSION: v0.10.4
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22

      - name: Set Importer StartDate
        run: |
          # Set start date to 60 seconds before the first block timestamp in the network
          url="https://${NETWORK}.mirrornode.hedera.com/api/v1/blocks?limit=1&order=asc"
          firstTimestamp=$(curl -s "${url}" | jq -r .blocks[0].timestamp.from)
          if [[ -z "${firstTimestamp}" ]]; then
            echo "Unable to get first block timestamp"
            exit 1
          fi

          startSecs=$((${firstTimestamp%.*}-60))
          startDate=$(date --date="@${startSecs}" -Iseconds -u | grep -o -e '^[0-9T:-]\+')
          startDate="${startDate}Z"
          echo "STARTDATE=${startDate}" >> $GITHUB_ENV
          echo "Set importer startDate to ${startDate}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          driver-opts: network=host
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["https://hub.mirror.docker.lat.ope.eng.hashgraph.io"]
          version: latest

      - name: Build Image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          build-args: GIT_REF=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ./rosetta/container
          github-token: ${{ secrets.GITHUB_TOKEN }}
          load: true
          provenance: false
          push: false
          tags: "${{ env.MODULE }}:${{ github.sha }}"

      - name: Importer Configuration
        run: echo "${{ secrets.ROSETTA_IMPORTER_CONFIG }}" | base64 -d > ${{ github.workspace }}/application_importer.yml

      - name: Rosetta Configuration
        run: echo "${{ secrets.ROSETTA_ROSETTA_CONFIG }}" | base64 -d > ${{ github.workspace }}/application_rosetta.yml

      - name: Run Mirror Node in Online Mode
        run: |
          ONLINE_CONTAINER_ID=$(docker run -d -e HIERO_MIRROR_IMPORTER_STARTDATE=${STARTDATE} \
            -e NETWORK=${NETWORK} \
            -e HIERO_MIRROR_ROSETTA_RESPONSE_MAXTRANSACTIONSINBLOCK=4 \
            -v ${{ github.workspace }}/application_importer.yml:/app/importer/application.yml \
            -v ${{ github.workspace }}/application_rosetta.yml:/app/rosetta/application.yml \
            -p 5700:5700 "${MODULE}:${{ github.sha }}")
          echo "ONLINE_CONTAINER_ID=$ONLINE_CONTAINER_ID" >> $GITHUB_ENV

      - name: Wait for Mirror Node to Start Syncing
        run: ./scripts/wait-for-mirror-node.sh
        env:
          MAX_WAIT_SECONDS: 900

      - name: Rosetta CLI Configuration
        working-directory: ./rosetta/scripts/validation/${{ env.NETWORK }}
        run: |
          # set start index to genesis index + 1
          body='{"network_identifier": {"blockchain": "Hedera", "network": "'${NETWORK}'"}}'
          startIndex=$(curl -sL -d "${body}" http://localhost:5700/network/status | jq '.genesis_block_identifier.index+1')
          echo "Setting data start_index to $startIndex"
          jq --argjson startIndex $startIndex '.data.start_index=$startIndex' validation.json > tmp.json && \
            mv tmp.json validation.json

      - name: Run Rosetta CLI Validation
        working-directory: ./rosetta/scripts/validation
        run: ./run-validation.sh ${NETWORK} data

      - name: Run Rosetta Postman API Tests
        working-directory: ./charts/hedera-mirror-rosetta
        run: |
          npm install -g newman
          newman run postman.json

      - name: Show Container Log
        if: ${{ failure() }}
        run: |
          echo "Logs for online container ${ONLINE_CONTAINER_ID}"
          [[ -n "${ONLINE_CONTAINER_ID}" ]] && docker logs ${ONLINE_CONTAINER_ID} || true
