# SPDX-License-Identifier: Apache-2.0

name: WRB Differential

on:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/actions/run-e2e/**"
      - ".github/workflows/wrb-differential.yaml"
  push:
    tags:
      - "v*"
  schedule:
    - cron: "0 23 * * *"

permissions:
  contents: read
  packages: read
  pull-requests: read

jobs:
  differential:
    runs-on: hiero-mirror-node-linux-large
    timeout-minutes: 50
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run end-to-end tests
        uses: ./.github/actions/run-e2e
        with:
          build-changed-modules-only: ${{ github.event_name != 'schedule' && 'true' || 'false' }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          image-source: jvm
          mode: wrb
          run-k6: "false"
          stream-type: BLOCK
